feat: Add VM commands
krystal/katapult-cli pull request #17
Opened 2021-07-21 12:07 UTC by JakeMakesStuff

2021-07-23 11:05 UTC, jimeh requested changes

2021-07-23 11:05 UTC, jimeh commented on cmd/katapult/vms.go
> +					}
I don't think this check is needed. As far as I know, VMs will always have a FDQN value.

2021-07-23 11:05 UTC, jimeh commented on cmd/katapult/vms_test.go
> +func TestVMs_List(t *testing.T) {
There's no test case for what happens if no org ID or sub-domain is provided.

2021-07-23 11:05 UTC, jimeh commented on cmd/katapult/vms_test.go
> +	tests := []struct {
There's no test case for when no VM ID or FQDN is provided. The other power-state tests are also missing such a test case.

2021-07-26 10:01 UTC, JakeMakesStuff commented on cmd/katapult/vms.go
> +			}
> Ah, not to mention the Org ID / SubDomain should probably be read from the config / environment vars too, meaning it defaults to what's pulled out of config, and the arg/flag lets you override it, or specify it if you don't have one configured.

I have went ahead and made an issue for this. 👍

2021-07-26 10:02 UTC, JakeMakesStuff commented on cmd/katapult/vms.go
> +			_, resp, err := client.Start(cmd.Context(), ref)
> Out of scope for this PR I think, so I'm just mentioning it for future reference;
> 
> We will eventually need a `--wait` flag or something similar on these power state commands, to have them wait for the returned task object to be marked as completed. Effectively blocking until the operation has completed and the VM is in the new and expected state.

I have went ahead and made an issue for this. 👍

2021-07-27 09:52 UTC, strideynet approved these changes

2021-07-27 10:14 UTC, jimeh requested changes
This is looking good, only thing missing (which I missed myself last time around 🤦‍♂️), are test cases for the power state commands for when a VM does not exist.

2021-07-27 11:22 UTC, jimeh requested changes

2021-07-27 11:22 UTC, jimeh commented on cmd/katapult/vms_test.go
> +		return katapult.ErrNotFound
This should be a `core.ErrVirtualMachineNotFound` to match what the go-katapult package returns when looking up Virtual Machines that don't exist.

```suggestion
		return core.ErrVirtualMachineNotFound
```

The error chain for `core.ErrVirtualMachineNotFound` is: 

- `katapult.Err`
  - `katapult.ErrResponse`
    - `katapult.ErrNotFound`
      - `katapult.ErrResourceNotFound`
        - `core.ErrVirtualMachineNotFound`

It's a bit long, but it ensures that it's easy to target error handling at any specific level you might care about.

2021-08-04 14:41 UTC, jimeh approved these changes
👍

2021-08-04 15:09 UTC, merged